version: "3.7"

services:
  api:
    container_name: "Excelante-api"
    image: golang:1.13
    working_dir: /api
    volumes:
    - ".:/api"
    entrypoint: ["./entrypoint.sh", "reflex", "-c", "reflex.conf"]
